apiVersion: v1
kind: Namespace
metadata:
  name: whatap-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatap
  namespace: whatap-monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whatap-server-monitoring
  namespace: whatap-monitoring
  labels:
    name: whatap-server-monitoring
spec:
  selector:
    matchLabels:
      name: whatap-server-monitoring
  template:
    metadata:
      labels:
        name: whatap-server-monitoring
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: whatap-server-monitoring
          image: whatap/server_mon
          imagePullPolicy: Always
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 350Mi
              cpu: 200m
          env:
            - name: WHATAP_LICENSE
              value: ""
            - name: WHATAP_HOST
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /whatap_conf
              name: whatap-config-volume
            - name: hostfs
              mountPath: /hostfs
              readOnly: true              
      volumes:
        - name: whatap-config-volume
          emptyDir: {}
        - hostPath:
            path: /
          name: hostfs
      serviceAccount: whatap


