
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whatap-node-agent
  namespace: whatap-monitoring
  labels:
    name: whatap-node-agent
spec:
  selector:
    matchLabels:
      name: whatap-node-agent
  template:
    metadata:
      labels:
        name: whatap-node-agent
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: whatap-node-helper
          image: registry.whatap.io:5000/whatap_dev:10415
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 350Mi
              cpu: 200m
          ports:
            - name: helperport
              containerPort: 6801
          command: ['/data/agent/node/cadvisor_helper', '-port','6801']
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: dockerdomainsocket
              mountPath: /var/run/docker.sock
            - name: rootfs-proc
              mountPath: /rootfs/proc
              readOnly: true 
            - name: rootfs-var
              mountPath: /rootfs/var
              readOnly: true
            - name: rootfs-sys
              mountPath: /rootfs/sys
              readOnly: true 
            - name: hostsys
              mountPath: /sys
              readOnly: true
            - name: hostdiskdevice
              mountPath: /dev/disk
              readOnly: true
            
        - name: whatap-node-agent
          image: registry.whatap.io:5000/whatap_dev:10455
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 350Mi
              cpu: 200m
          ports:
            - name: nodeport
              containerPort: 6600
          command: ['/bin/entrypoint.sh']
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WHATAP_LICENSE
              value: "x2t0gudg07gde-x3lr4m5mi7rsn2-z29tpre74luufj"
            - name: WHATAP_HOST
              value: "192.168.1.102"
            - name: WHATAP_PORT
              value: "6600"
            - name: HOST_PREFIX
              value: "/rootfs"
          volumeMounts:
            - name: rootfs-proc
              mountPath: /rootfs/proc
              readOnly: true
            - name: rootfs-var
              mountPath: /rootfs/var
              readOnly: true
            - name: start-script-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - mountPath: /whatap_conf
              name: whatap-config-volume              
        
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockerdomainsocket
        - hostPath:
            path: /proc
          name: rootfs-proc
        - hostPath:
            path: /var
          name: rootfs-var
        - hostPath:
            path: /sys
          name: rootfs-sys
        - hostPath:
            path: /sys
          name: hostsys
        - hostPath:
            path: /var/lib/docker
          name: hostdocker
        - hostPath:
            path: /dev/disk
          name: hostdiskdevice
        - name: start-script-volume
          configMap:
            defaultMode: 0700
            name: node-start-script
        - hostPath:
            path: /home/whatap/whatap_node_config
          name: whatap-config-volume
      serviceAccount: whatap
