---
- name: Install Whatap Server Monitorning
  vars:
    updateonly: true
  hosts: all
  become: true
  tasks:
  - name: Add Repository Ubuntu
    include_tasks: tasks/Ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Add Repository Amazon
    include_tasks: tasks/Amazon.yml
    when: ansible_distribution == 'Amazon'
  - name: Add Repository CentOS
    include_tasks: tasks/CentOS.yml
    when: ansible_distribution == "CentOS"
  - name: Add Repository SUSE
    include_tasks: tasks/Suse.yml
    when: ansible_distribution == 'SLES'
  - name: Add Repository Windows
    include_tasks: tasks/Windows.yml
    when: ansible_distribution == 'Windows'
