---
- name: Add key
  rpm_key:
    key: http://repo.whatap.io/centos/release.gpg
    state: latest
- name: Add repository
  yum_repository:
    name: whatap packages for enterprise linux
    description: whatap
    baseurl: http://repo.whatap.io/centos/latest/$basearch
    gpgcheck: no
- name: Install whatap-infra
  yum:
    name: whatap-infra
    state: latest
    update_cache: yes
- name: Start whatap-infra monitorning
  shell: "{{ item }}"
  with_items:
    - 'echo license={{whatap_license}} | sudo tee /usr/whatap/infra/conf/whatap.conf'
    - 'echo "whatap.server.host={{whatap_server_host}}" |sudo tee -a /usr/whatap/infra/conf/whatap.conf'
    - 'echo "createdtime=`date +%s%N`" | sudo tee -a /usr/whatap/infra/conf/whatap.conf'
  when:
    not updateonly
- name: service start
  service:
    name: whatap-infra
    state: restarted
