---
- name: Add key
  rpm_key:
    state: present
    key: http://repo.whatap.io/centos/release.gpg
- name: Add repository
  yum:
    name: http://repo.whatap.io/centos/5/noarch/whatap-repo-1.0-1.noarch.rpm
    state: latest
- name: Install whatap-infra
  yum:
    name: whatap-infra
    state: latest
    update_cache: yes
- name: Start whatap-infra monitorning
  shell: "{{ item }}"
  with_items:
    - 'echo license={{whatap_license}} | sudo tee /usr/whatap/infra/conf/whatap.conf'
    - 'echo "whatap.server.host={{whatap_server_host}}" |sudo tee -a /usr/whatap/infra/conf/whatap.conf'
    - 'echo "createdtime=`date +%s%N`" | sudo tee -a /usr/whatap/infra/conf/whatap.conf'
  when:
    not updateonly
- name: service start
  service:
    name: whatap-infra
    state: restarted
