apiVersion: v1
kind: Namespace
metadata:
  name: whatap-monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-start-script
  namespace: whatap-monitoring
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash

    cat >/whatap_conf/whatap.telegraf.conf <<EOL
    [global_tags]
      pod = "$POD_NAME"
      ip = "$POD_IP"
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false

    [[outputs.whatap]]
      license = "whatap license string"
      pcode = 000
      servers = ["tcp://whatap ip:6600"]

    [[inputs.cloudwatch]]
      region = "ap-northeast-2"
      access_key = "AWS Access Key"
      secret_key = "AWS Secret Key"

      period = "1m"
      delay = "1m"
      interval = "1m"
      namespace = "AWS/ApplicationELB"
    EOL

    /data/agent/telegraf/telegraf --config /whatap_conf/whatap.telegraf.conf
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatap-telegraf-agent
  namespace: whatap-monitoring
spec:
  template:
    metadata:
      labels:
        name: whatap-telegraf-agent
    spec:
      containers:
        - name: whatap-telegraf-agent
          image: whatap/kube_mon
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 350Mi
              cpu: 200m
          command: ['/bin/entrypoint.sh']
          volumeMounts:
            - name: start-script-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - mountPath: /whatap_conf
              name: whatap-config-volume              
          env:
            - name: POD_IP
            valueFrom: {fieldRef: {fieldPath: status.podIP}}
            - name: POD_NAME
            valueFrom: {fieldRef: {fieldPath: metadata.name}}
      volumes:
        - name: start-script-volume
          configMap:
            defaultMode: 0700
            name: telegraf-start-script
        - name: whatap-config-volume
          emptyDir: {}        

